version: '3'
services:
  bind:
    build: ./bind_9.16
    container_name: bind_9.16
    volumes:
      - bind_9.16-etc:/etc/bind
      - bind_9.16-log:/var/log
      - bind_9.16-cache:/var/cache/bind
      - bind_9.16-lib:/var/lib/bind
    ports:
      - 53:53/tcp
      - 53:53/udp
    expose: 
      - 953/tcp
    restart: always

volumes:
  bind_9.16-etc:
  bind_9.16-log:
  bind_9.16-cache:
  bind_9.16-lib:

          #+        --name=bind9 \

          #+        --restart=always \

          # +       --publish 53:53/udp \
          # +      --publish 53:53/tcp \
          # +      --publish 127.0.0.1:953:953/tcp \

          #        --volume /etc/bind \
          #        --volume /var/cache/bind \
          #        --volume /var/lib/bind \
          #        --volume /var/log \

          #+        internetsystemsconsortium/bind9:9.16
